t=[-20:20];
y=[zeros(1,20) 1 zeros(1,20)];
subplot(3,1,1);
plot(t,y);
xlabel('Time');
ylabel('Amplitude');
title('Unit Impulse Signal');
subplot(3,1,2);
plot(t-5,y);
xlabel('Time');
ylabel('Amplitude');
title('Advanced Unit Impulse Signal');
subplot(3,1,3);
plot(t+5,y);
xlabel('Time');
ylabel('Amplitude');
title('Delayed Unit Impulse Signal');
